### ISSUE TITLE
Efficient use of Real Estate on the Dashboard Landing Page

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#272]
_Originally reported by_: @jagus7

Since not all items will be listed on the first page under “Explore” it would be good to limit the number of these items on that page so that the message “As the CTD2 Network continues to refine the Dashboard,…..” with links to contact CTD2 and to the glossary will be visible without having to scroll down. Otherwise, it is likely to be missed.

**Comment by kcs3** [comment]
This refers to the footer at the bottom of the web page.  Rather than limiting the content of the landing page, the links to the Glossary, Policies etc. could be included in the Resources menu item at the top, perhaps some in a submenu?  But definitely the Glossary should be given a prominent spot in the Resources menu.

**Comment by kcs3** [comment]
These issues dealt with in the latest major releases which removed most content from the landing page (3.0, 3.1).
