### ISSUE TITLE
Define and implement search behavior when term itself is composed of multiple words

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#353]
In the Dashboard feedback document, under Dashboard Home Page, item 7, the case of "pancreatic ductal adenocarcinoma" and its synonyms is raised.  In that comment, the reviewer states that these should not give separate search results, as they do now.  As these are all matches on Dashboard terms, we may not be able to change this.

However, it also brings up the case of how to treat terms that are themselves composed of multiple words in our new "AND-based" search capability.  Currently, in the new implementation, search for "pancreatic ductal adenocarcinoma" does not result in the "observations matching all terms" section to appear.  This can be regarded as OK as the match is actually at the level of terms, not words, and only one term has been matched.

If we now add "KRAS" to the search, there are observations which contain both terms, and they should appear under "observations matching all terms".  However, they do not currently appear.

**Comment by kcs3** [comment]
This is a continuation of work on search improvements started in #343.

**Comment by kcs3** [comment]
Searching on the term "pancreatic ductal carncinoma" returns many related terms, e.g. gastric adenocarcinoma.  For the intersection of multiple terms, e.g. "pancreatic ductal carcinoma" and KRAS, we will only consider terms that are an exact substring of the original search phrase.  Thus "gastric adenocarcinoma" which instroduces a new word "gastric", will not be further considered in the intersection.  

We will not consume search terms as they are matched, that is, a given word in the search may match more than one term, as long as that term does not introduce any new words.

**Comment by zhouji2013** [comment]
The algorithm to produce the list of observations that contain the intersection of searching terms:

1. From the searching result of **subjects**, the **searching terms** are decided as the subject names that are also a substring of the compete query string. For example, if you enter "pancreatic ductal adenocarcinoma kras", we find three terms "pancreatic ductal adenocarcinoma", "adenocarcinoma", and "kras".
2. If some of the terms are the proper substrings of other terms, they are excluded from consideration when producing the intersection. In the above example, "adenocarcinoma" is removed and we use two terms, "pancreatic ductal adenocarcinoma" and "kras", in the next steps.
3. If there is only one term, we will not report any observation; otherwise, the observations that contain **all** the search terms are reported. In the above example, each of the observations reported should contained both "pancreatic ductal adenocarcinoma" and "kras".

**Comment by kcs3** [comment]
The new multi-term search function is working correctly, as described above by Zhou.

**Comment by kcs3** [comment]
Tested and confirmed working in production Dashboard version 2.50.
