### ISSUE TITLE
prioritize search results by similarity to all searched terms

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#376]
It appears that search results are not ranked in any particular way currently.  For example, searching on "B cell" (no quotes) returns numerous terms at the top of the results with B but not cell in them.  Currently the user can fix this by enclosing the terms in quotes.

Examine if ranking results without quotes is feasible and desirable.

This is a follow-up to issue #356, which has additional examples.

**Comment by kcs3** [comment]
Let's add text to the search tooltip advising about use of quotes to narrow search.

**Comment by zhouji2013** [comment]
I entered this comment to document what we intend to do for an tentative implementation at this point:

1. The ranking should follow the description from issue #487. The attached document there, section "Detailed workflow", item 3, the first sub-item "Subjects" contains the requirement regarding ranking: "Subjects are listed in decreasing order of their c_Yi count, to ensure that the most relevant matches (i.e., those that match the most search terms) appear at the top. Ties are broken by total observation count, i.e., subjects associated with a larger number of observations are listed first." To put in a brief way: rank by the number of terms matched; if there is a tie, rank by the number of observations within the group.
2. Add a question mark icon next to the text that reads (just a specific example below): "Showing 1 to 3 of 3 entries". And include hover text which explains how the ranking is done.
3. Do away with the question marks next to the number of observations.
4. Show the results as follows:
             208 observations
              (from 9 Centers)

**Comment by arisf** [comment]
As far as I can tell, the prioritization works per the specification. I did notice a couple of small issues that require attention:

**Issue 1**:
For searches leading to many hits, the warning message reads something like "Only top 100 of XXX subjects are listed in the table below". However, the text that appears just above the results table states "Showing 1 to 10 of 200 entries", instead of "Showing 1 to 10 of 200 entries".

**Issue 2**:
Execute a search using the search term “liver”. After the results are back, initiate an ontology search. The search apparently hangs, with the following error message:
DataTables warning: table id=searched-submissions - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by arisf** [comment]
Execute a search using the search term “liver”. After the results are back, initiate an ontology search. At the top of the results page the link reads "See one matched submission from one center". However, there are 4 matched submissions, not one.

**Comment by arisf** [comment]
Tested on development servicer, all the reported issues have been addressed.

**Comment by arisf** [comment]
Verified on production server.
