### ISSUE TITLE
direct story link not always showing

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#385]
Stories should have a special link that appears just below the observation summary, so that the user does not need to find the story link in the evidence section.  This is working for some submissions but not others.
For example, the story link is not seen in the observation
https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20180329-fhcrc-novel-targets-head-and-neck--0
but it is seen in
https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20150409-utmda-pik3r1-0

**Comment by zhouji2013** [comment]
The different behavior is caused by submission data inconsistency. In file 20180329-fhcrc_novel_targets_head_and_neck_cancer.txt, the column for the file evidence of the story is called 'story'. In contrast, in 20150409-utmda_pik3r1.txt, the column name is 'story_location'. On the observation page, column name 'story_location' is checked to find storyFilePath (line 800 ctd2.js), and if it is not empty, the link mentioned in the bug report is shown (line 934 ctd2.js). Technically, we could ignore that name to make this link shown because we do have the correct file path anyway. In other words, the column name possibly **should** be ignored. However, if that is the case, we should consistently and clearly ignore that column name everywhere instead of only bypassing it in this particular scenario.

**Comment by zhouji2013** [comment]
Just in case we need investigate more, here are the queries I used:
* find the observation with a given column name
  * SELECT * FROM observed_evidence_role join observation_template on observation_template.id=observed_evidence_role.observationTemplate_id WHERE columnName = 'story_location'
* find the observation's column name 
  * SELECT * FROM observed_evidence_role join observation_template on observation_template.id=observed_evidence_role.observationTemplate_id WHERE description like 'Beyond DNA Sequencing%'

**Comment by kcs3** [comment]
The data appears to be fixed now.
