### ISSUE TITLE
Add support for string-db to gene cart

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#472]
string-db.org has a web API described at https://string-db.org/help/api/.

We need to, at minimum, support calls to the API with multiple human gene symbols.

**Comment by zhouji2013** [comment]
What is supposed to happen after the user clicks "Submit" for STRING as described in  #453 ? Call API to do what?

**Comment by kcs3** [comment]
If we can use the URL call to just open the result in a new web page that would be good.

**Comment by zhouji2013** [comment]
To get to a web page instead of using API, here are some details found by Aris:

Here is a simple URL to retrieve interactions for TP53: https://string-db.org/network/homo_sapiens/TP53

Some of the rules for building URLs that link to networks are described here: https://string-db.org/cgi/help.pl?sessionId=nSQ3VCldv4Xe

under “FAQ” -> “How do I link to STRING networks?”. E.g., here is a URL to link to an interaction network involving genes TP53, FOXM1, and BCL6: https://string-db.org/cgi/network.pl?identifiers=TP53%0dFOXM1%0dBCL6

This is *almost* exactly what we need (where we would replace the three genes above with the symbols from the gene cart).

**Comment by zhouji2013** [comment]
To have organism pre-selected, use a link like this https://string-db.org/cgi/network.pl?identifiers=TP53%0DFOXM1%0DBCL6&species=9606 , but the user still needs to click "Continue -" to get to the network view.

To get the network data directly using gene symbols, we can use API call like this https://string-db.org/api/tsv/network?identifiers=TP53%0dFOXM1%0dBCL6

**Comment by zhouji2013** [comment]
STRING DB apparently does not support out-of-box the feature as we want, namely using a URL to show the network based on gene symbols, but I came up withe a solution:

1. use API to look up the identifiers for given gene symbols, using URL like this https://string-db.org/api/tsv/get_string_ids?identifiers=TP53&species=9606 or https://string-db.org/api/tsv/get_string_ids?identifiers=FOXM1&species=9606
2. get the network view directly with identifiers instead of gene symbols, with a URL like this
https://string-db.org/cgi/network.pl?identifiers=9606.ENSP00000342307%0d9606.ENSP00000269305

This matches the result as the user clicks "Continue ->" with all the default choices.

For more details, see https://string-db.org/cgi/help.pl?subpage=api%23mapping-identifiers and https://string-db.org/cgi/help.pl?subpage=api%23getting-the-string-network-interactions

**Comment by arisf** [comment]
Zhou, great, this will work fine.

**Comment by zhouji2013** [comment]
Apparently the behavior of string-db changed since the last solution. We need to review the solution again.

**Comment by zhouji2013** [comment]
> 
> 
> Apparently the behavior of string-db changed since the last solution. We need to review the solution again.

Fortunately the previous version is still available through a version-specific URL. See https://string-db.org/cgi/access?sessionId=bMiF9FsVzgm1&footer_active_subpage=archive

**Comment by kcs3** [comment]
tested on test server, works fine, opens a new page for the STRING server using the query gene symbols.

**Comment by kcs3** [comment]
Tested on production server, works fine.
