### ISSUE TITLE
Create master download of Dashboard subject data

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#509]
Create a simple file format to use to export all Dashboard subject data.  Each row in the file will correspond to one observation.  The number of columns for each row will depend on the number of subjects represented in that row. Detailed specification attached below.

[CTD2 Dashboard Master Download.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8172282/CTD2.Dashboard.Master.Download.docx)

**Comment by arisf** [comment]
* For column "Submission date" please change values from format "4/29/2013  12:00:00 AM" to format "4/29/2013", i.e., remove the time portion.
* For column "Observation URL" please use the full URL, per specification. I.e., instead of "observation/20130429-dfci-ataris-analysis-0", the value should be "https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20130429-dfci-ataris-analysis-0"

**Comment by arisf** [comment]
Confirmed on development server.
